# Generated by Django 2.2 on 2020-06-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_libro_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='localizacion',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
